platform:ios,'9.1'
target 'RxText01' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift'
    pod 'RxCocoa'

    pod 'SnapKit'
    pod 'YYKit'
    pod 'Timepiece'

    pod 'JTAppleCalendar'
    
    pod 'CVCalendar'
 
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end
