target 'FmOnlinePayApi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftMoya
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'


end







