platform:ios,'9.0'
target 'ZHX_major' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftMoya
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  
  # IQKeyboard
  pod 'IQKeyboardManagerSwift'

  # Pods Color
  pod 'DynamicColor', '~> 3.3'  

  # KingFisher Image
  pod 'Kingfisher', '~> 4.0.0'
  pod 'FSPagerView', '~> 0.7.0'

  #progress
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'
  
  pod 'SnapKit', '~> 4.0.0'
  
  pod 'QRCodeReader.swift','~> 8.0.4'
  
  #refresh
  pod 'MJRefresh'
  
  pod 'DeviceGuru'

  pod "ESTabBarController-swift"

  pod 'NoticeBar'
  
  #Calendar
#  pod 'CVCalendar','~> 1.6.1'

  #RealNetworkStatus from ping
  pod ‘RealReachability’

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end




