
platform:ios,'9.1'
target 'BLEDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'BabyBluetooth'
pod 'SVProgressHUD'

pod 'MBProgressHUD'
pod 'CryptoSwift'


pod 'SwiftyBluetooth'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end












